module ElasticGraph
  class Indexer
    class ConfigSupertype
      attr_reader latency_slo_thresholds_by_timestamp_in_ms: ::Hash[::String, ::Integer]
      attr_reader skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]]

      def initialize: (
        latency_slo_thresholds_by_timestamp_in_ms: ::Hash[::String, ::Integer],
        skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]]) -> void

      def with: (
        ?latency_slo_thresholds_by_timestamp_in_ms: ::Hash[::String, ::Integer],
        ?skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]]) -> Config

      def self.members: () -> ::Array[::Symbol]
    end

    class Config < ConfigSupertype
      extend _BuildableFromParsedYaml[Config]
      EXPECTED_KEYS: ::Array[::String]
    end
  end
end
