module ElasticGraph
  class Indexer
    class FailedEventError < Errors::Error
      attr_reader main_message: ::String
      attr_reader event: ::Hash[::String, untyped]
      attr_reader operations: ::Set[_Operation]
      attr_reader versioned_operations: ::Array[_Operation]
      attr_reader id: ::String
      attr_reader full_id: ::String
      attr_reader op: ::String
      attr_reader version: ::Integer
      attr_reader record: ::Hash[::String, untyped]?

      def self.from_failed_operation_result: (
        Operation::Result,
        ::Set[_Operation]
      ) -> FailedEventError

      def initialize: (
        event: ::Hash[::String, untyped],
        operations: ::Set[_Operation],
        main_message: ::String
      ) -> void
    end
  end
end
