module ElasticGraph
  class GraphQL
    module Aggregation
      class Computation
        attr_reader source_field_path: fieldPath
        attr_reader computed_index_field_name: ::String
        attr_reader detail: SchemaArtifacts::RuntimeMetadata::ComputationDetail

        def key: (aggregation_name: ::String) -> ::String
        def clause: () -> ::Hash[::String, untyped]

        def initialize : (
          source_field_path: fieldPath,
          computed_index_field_name: ::String,
          detail: SchemaArtifacts::RuntimeMetadata::ComputationDetail
        ) -> void

        def with: (
          ?source_field_path: fieldPath,
          ?computed_index_field_name: ::String,
          ?detail: SchemaArtifacts::RuntimeMetadata::ComputationDetail
        ) -> instance
      end
    end
  end
end
