# Copyright 2024 Block, Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# frozen_string_literal: true

source "https://rubygems.org"

%w[
  admin
  apollo
  datastore_core
  elasticsearch
  graphql
  indexer
  json_schema
  rack
  schema_artifacts
  schema_definition
  support
].each do |suffix|
  gem "elasticgraph-#{suffix}", path: "elasticgraph-#{suffix}"
end

gem "rackup", "~> 2.2"
gem "webrick", "~> 1.9"
