module ElasticGraph
  class GraphQL
    # Note: this is a partial signature definition (`schema.rb` is ignored in `Steepfile`)
    class Schema
      attr_reader graphql_schema: ::GraphQL::Schema
      attr_reader element_names: SchemaArtifacts::RuntimeMetadata::SchemaElementNames

      def initialize: (
        graphql_schema_string: ::String,
        config: Config,
        runtime_metadata: SchemaArtifacts::RuntimeMetadata::Schema,
        index_definitions_by_graphql_type: ::Hash[::String, ::Array[DatastoreCore::_IndexDefinition]],
        graphql_gem_plugins: ::Hash[::Class, ::Hash[::Symbol, untyped]]
      ) { (Schema) -> Resolvers::GraphQLAdapter } -> void

      def type_from: (::GraphQL::Schema::_Type) -> Type
      def type_named: (::String | ::Symbol) -> Type
      def field_named: (::String | ::Symbol, ::String | ::Symbol) -> Field
      def indexed_document_types: () -> ::Array[Type]
    end
  end
end
