module ElasticGraph
  DATASTORE_DATE_FORMAT: ::String
  DATASTORE_DATE_TIME_FORMAT: ::String
  TIMEOUT_MS_HEADER: ::String
  INT_MIN: ::Integer
  INT_MAX: ::Integer
  JSON_SAFE_LONG_MAX: ::Integer
  JSON_SAFE_LONG_MIN: ::Integer
  LONG_STRING_MIN: ::Integer
  LONG_STRING_MAX: ::Integer
  DEFAULT_MAX_KEYWORD_LENGTH: ::Integer
  DEFAULT_MAX_TEXT_LENGTH: ::Integer
  EVENT_ENVELOPE_JSON_SCHEMA_NAME: ::String
  SINGLETON_CURSOR: ::String
  GRAPHQL_SCHEMA_FILE: ::String
  JSON_SCHEMAS_FILE: ::String
  DATASTORE_CONFIG_FILE: ::String
  RUNTIME_METADATA_FILE: ::String
  ROLLOVER_INDEX_INFIX_MARKER: ::String
  JSON_SCHEMAS_BY_VERSION_DIRECTORY: ::String
  JSON_SCHEMA_VERSION_KEY: ::String
  DERIVED_INDEX_FAILURE_MESSAGE_PREAMBLE: ::String
  INDEX_DATA_UPDATE_SCRIPT_ID: ::String
  OLD_INDEX_DATA_UPDATE_SCRIPT_ID: ::String
  UPDATE_WAS_NOOP_MESSAGE_PREAMBLE: ::String
  SELF_RELATIONSHIP_NAME: ::String
  VALID_LOCAL_TIME_REGEX: ::Regexp
  VALID_LOCAL_TIME_JSON_SCHEMA_PATTERN: ::String
  LIST_COUNTS_FIELD: ::String
  LIST_COUNTS_FIELD_PATH_KEY_SEPARATOR: ::String
  DATASTORE_PROPERTYLESS_OBJECT_TYPES: ::Set[::String]
  GRAPHQL_NAME_WITHIN_LARGER_STRING_PATTERN: ::Regexp
  GRAPHQL_NAME_PATTERN: ::Regexp
  GRAPHQL_NAME_VALIDITY_DESCRIPTION: ::String
  STOCK_GRAPHQL_SCALARS: ::Set[::String]
  JSON_META_SCHEMA: ::String
  DATASTORE_BULK_FILTER_PATH: ::String
  GRAPHQL_LAMBDA_AWS_ARN_HEADER: ::String
end
