module ElasticGraph
  module SchemaArtifacts
    module RuntimeMetadata
      class ComputationDetailSupertype
        attr_reader function: ::Symbol
        attr_reader empty_bucket_value: ::Numeric?

        def initialize: (
          function: ::Symbol,
          empty_bucket_value: ::Numeric?
        ) -> void

        def with: (
          ?function: ::Symbol,
          ?empty_bucket_value: ::Numeric?
        ) -> instance

        def self.new:
          (function: ::Symbol, empty_bucket_value: ::Numeric?) -> instance
          | (::Symbol, ::Numeric?) -> instance
      end

      class ComputationDetail < ComputationDetailSupertype
        FUNCTION: "function"
        EMPTY_BUCKET_VALUE: "empty_bucket_value"

        def self.from_hash: (::Hash[::String, untyped]) -> ComputationDetail
        def to_dumpable_hash: () -> ::Hash[::String, untyped]
      end
    end
  end
end
