module ElasticGraph
  module JSONSchema
    class ValidatorFactory
      attr_reader root_schema: ::JSONSchemer::Schema
      @raw_schema: ::Hash[::String, untyped]
      @sanitize_pii: bool
      @validators_by_type_name: ::Hash[::String, Validator]
      def initialize: (schema: ::Hash[::String, untyped], sanitize_pii: bool) -> void
      def validator_for: (::String) -> Validator
      def with_unknown_properties_disallowed: (?except: ::Array[::String]) -> ValidatorFactory

      private

      def prevent_unknown_properties!: (
        untyped,
        allow_paths: ::Array[::Array[::String]],
        ?parent_path: ::Array[::String]
      ) -> void
    end
  end
end
