datastore:
  client_faraday_adapter:
    name: httpx
    require: httpx/adapters/faraday
  clusters:
    main:
      url: http://localhost:9444
      backend: elasticsearch
      settings: {}
  index_definitions:
    artists: &main_index_settings
      query_cluster: "main"
      index_into_clusters: ["main"]
      ignore_routing_values: []
      custom_timestamp_ranges: []
      setting_overrides:
        number_of_shards: 1
      setting_overrides_by_timestamp: {}
    venues: *main_index_settings
  max_client_retries: 3
graphql:
  default_page_size: 50
  max_page_size: 500
logger:
  device: stderr
indexer:
  latency_slo_thresholds_by_timestamp_in_ms: {}
schema_artifacts:
  directory: config/site/examples/music/schema_artifacts
query_registry:
  # Allow any query by any client since this is for local use.
  allow_unregistered_clients: true
  allow_any_query_for_clients: []
  path_to_registry: config/site/examples/music/queries
