module ElasticGraph
  module Apollo
    module SchemaDefinition
      module GraphQLSDLEnumeratorExtension: ElasticGraph::SchemaDefinition::SchemaElements::GraphQLSDLEnumerator
      end
    end
  end
end
