module ElasticGraph
  module Apollo
    module SchemaDefinition
      module StateExtension: ElasticGraph::SchemaDefinition::State
        attr_accessor apollo_directive_definitions: ::Array[::String]

        def self.extended: (ElasticGraph::SchemaDefinition::State & StateExtension) -> void
      end
    end
  end
end
