module ElasticGraph
  class GraphQL
    module ScalarCoercionAdapters
      class DateTime
        extend SchemaArtifacts::_ScalarCoercionAdapter[::String, ::String]
        PRECISION: ::Integer

        private

        def self.raise_coercion_error: (::String) -> bot
      end
    end
  end
end
