module ElasticGraph
  module Support
    module Threading
      def self.parallel_map:
        [K, V, O] (::Hash[K, V]) { ([K, V]) -> O } -> ::Array[O]
        | [I, O] (::Enumerable[I]) { (I) -> O } -> ::Array[O]
    end
  end
end
