module ElasticGraph
  module SchemaDefinition
    module Indexing
      module FieldType
        class Enum
          include _FieldType
          attr_reader enum_value_names: ::Array[::String]
          def initialize: (::Array[::String]) -> void
        end
      end
    end
  end
end
