module ElasticGraph
  module SchemaDefinition
    module Indexing
      module FieldType
        class Scalar
          include _FieldType
          attr_reader scalar_type: SchemaElements::ScalarType

          def initialize: (scalar_type: SchemaElements::ScalarType) -> Scalar
        end
      end
    end
  end
end
