module ElasticGraph
  module SchemaDefinition
    module Indexing
      module FieldType
        class UnionSuperType
          attr_reader subtypes_by_name: ::Hash[::String, Object]
          def self.new: (::Hash[::String, Object]) -> instance
        end

        class Union < UnionSuperType
          include _FieldType
        end
      end
    end
  end
end
