module ElasticGraph
  class Indexer
    module Operation
      class Upsert
        include _Operation
        attr_reader record_preparer: _RecordPreparer

        def initialize: (event, DatastoreCore::_IndexDefinition, _RecordPreparer) -> void

        private

        @metadata: ::Hash[::Symbol, untyped]?
        def metadata: () -> ::Hash[::Symbol, untyped]

        attr_reader prepared_record: ::Hash[::String, untyped]

        @to_datastore_bulk: datastoreBulkPayload?
        @metadata: ::Hash[::Symbol, untyped]?
        @doc_id: ::String?
        @routing_value_for_event: ::String?

        def ignore_custom_routing_for_event?: (::String) -> bool
      end
    end
  end
end
