module ElasticGraph
  module SchemaDefinition
    module Mixins
      module HasIndices
        attr_reader indices: ::Array[Indexing::Index]
        attr_accessor runtime_metadata_overrides: ::Hash[::Symbol, untyped]
        def index: (::String, ::Hash[::Symbol, ::String | ::Integer]) ?{ (Indexing::Index) -> void } -> ::Array[Indexing::Index]
        def indexed?: () -> bool
        def runtime_metadata: (::Array[SchemaArtifacts::RuntimeMetadata::UpdateTarget]) -> SchemaArtifacts::RuntimeMetadata::ObjectType
        def derived_indexed_types: () -> ::Array[Indexing::DerivedIndexedType]
        def derive_indexed_type_fields: (
          ::String,
          from_id: ::String,
          ?route_with: ::String,
          ?rollover_with: ::String
        ) ?{ ( Indexing::DerivedIndexedType) -> void } -> Indexing::DerivedIndexedType
        def root_query_fields: (plural: ::String, ?singular: ::String?) ?{ (SchemaElements::Field) -> void } -> void
        def plural_root_query_field_name: () -> ::String
        def singular_root_query_field_name: () -> ::String
        def root_query_fields_customizations: () -> (^(SchemaElements::Field) -> void)?
        def fields_with_sources: () -> ::Array[SchemaElements::Field]
        def indexing_fields_by_name_in_index: () -> ::Hash[::String, SchemaElements::Field]
      end
    end
  end
end
