#!/usr/bin/env ruby

require "erb"
require_relative "list_eg_gems"

module ElasticGraph
  class ReadmeRenderer
    PROJECT_ROOT = File.expand_path("..", __dir__)

    def initialize(template)
      @erb = ::ERB.new(template, trim_mode: "-")
    end

    def render
      @erb.result(binding)
    end

    def gem_specs
      @gem_specs ||= ::ElasticGraphGems.list.map do |gem_name|
        ::Gem::Specification.load("#{PROJECT_ROOT}/#{gem_name}/#{gem_name}.gemspec")
      end
    end

    def gem_categories
      @gem_categories ||= gem_specs.group_by do |spec|
        spec.metadata.fetch("gem_category") do
          raise "No category set for #{spec.name}."
        end
      end.map do |category, specs|
        category_info = CategoryInfo::BY_NAME.fetch(category) do
          raise "Unrecognized category: `#{category}` found on gems: #{specs.map(&:name)}."
        end
        GemCategory.new(category, category_info, specs, gem_specs)
      end
    end
  end

  class GemCategory < ::Data.define(:category_name, :info, :gem_specs, :all_eg_gem_specs)
    def mermaid_definition
      <<~MERMAID
        ```mermaid
        graph LR;
        #{mermaid_deps.join("\n")}
        #{mermaid_styles.join("\n")}
        #{mermaid_clicks.join("\n")}
        ```
      MERMAID
    end

    private

    def mermaid_deps
      gem_specs.filter_map do |spec|
        unless spec.runtime_dependencies.empty?
          deps = spec.runtime_dependencies.map(&:name).join(" & ")
          "    #{spec.name} --> #{deps}"
        end
      end
    end

    def mermaid_styles
      all_nodes = gem_specs.map(&:name) | gem_specs.flat_map { |spec| spec.runtime_dependencies.map(&:name) }
      all_nodes.map do |node|
        "    style #{node} #{style_for(node)};"
      end
    end

    def style_for(gem_name)
      # These colors were chosen to look good on GitHub in both light mode and dark mode.
      if gem_specs.any? { |spec| spec.name == gem_name }
        "color: DodgerBlue" # Basic "Blue" doesn't look good in dark mode.
      elsif all_eg_gem_specs.any? { |spec| spec.name == gem_name }
        "color: Green"
      else
        "color: Red"
      end
    end

    def mermaid_clicks
      gem_specs.flat_map { |spec| spec.runtime_dependencies.map(&:name) }.uniq.sort.filter_map do |gem_name|
        unless all_eg_gem_specs.any? { |spec| spec.name == gem_name }
          "click #{gem_name} href \"https://rubygems.org/gems/#{gem_name}\""
        end
      end
    end
  end

  class CategoryInfo < ::Data.define(:description, :discussion)
    BY_NAME = {
      "core" => new("Core Libraries", <<~EOS),
        These libraries form the core backbone of ElasticGraph that is designed to run in a production deployment. Every ElasticGraph deployment will need to use all of these.
      EOS

      "datastore_adapter" => new("Datastore Adapters", <<~EOS),
        These libraries adapt ElasticGraph to your choice of datastore (Elasticsearch or OpenSearch).
      EOS

      "extension" => new("Extensions", <<~EOS),
        These libraries extend ElasticGraph to provide optional but commonly needed functionality.
      EOS

      "lambda" => new("AWS Lambda Integration Libraries", <<~EOS),
        These libraries wrap the the core ElasticGraph libraries so that they can be deployed using AWS Lambda.
      EOS

      "local" => new("Local Development Libraries", <<~EOS)
        These libraries are used for local development of ElasticGraph applications, but are not intended to be deployed to production (except for `elasticgraph-rack`).
        `elasticgraph-rack` is used to boot ElasticGraph locally but can also be used to run ElasticGraph in any rack-compatible server (including a Rails application).
      EOS
    }
  end
end

renderer = ElasticGraph::ReadmeRenderer.new(DATA.read)
contents = renderer.render
readme_path = ::File.join(__dir__, "..", "README.md")

case ARGV.first
when "--verify"
  if ::File.read(readme_path) == contents
    puts "✅ README is up-to-date."
  else
    tmp_path = ::File.join(__dir__, "..", "tmp", "README.md")
    ::File.write(tmp_path, contents)

    diff = `git diff --no-index #{readme_path} #{tmp_path} #{" --color" unless ENV["CI"]}`

    puts "❌ README is out-of-date. Run `#{__FILE__}` to update it. Diff:"
    puts
    puts diff
    exit(1)
  end
when nil
  ::File.write(readme_path, contents)
  puts "README.md updated."
else
  raise "Unknown argument: #{ARGV.first}. Expected `--verify` or nothing."
end

__END__
# ElasticGraph

ElasticGraph is a general purpose, near real-time data query and search platform that is scalable and performant,
serves rich interactive queries, and dramatically simplifies the creation of complex reports. The platform combines
the power of indexing and search of Elasticsearch or OpenSearch with the query flexibility of GraphQL language.
Optimized for AWS cloud, it also offers scale and reliability.

ElasticGraph is a naturally flexible framework with many different possible applications. However, the main motivation we have for
building it is to power various data APIs, UIs and reports. These modern reports require filtering and aggregations across a body of ever
growing data sets. Modern APIs allow us to:

- Minimize network trips to retrieve your data
- Get exactly what you want in a single query. No over- or under-serving the data.
- Push filtering complex calculations to the backend.

## Libraries

ElasticGraph is designed to be modular, with a small core, and many built-in extensions that extend that core
for specific use cases. This minimizes exposure to vulnerabilities, reduces bloat, and makes ongoing upgrades
easier. The libraries that ship with ElasticGraph can be broken down into several categories.

<% gem_categories.each do |category| -%>
### <%= category.info.description %> (<%= category.gem_specs.size %> gems)

<%= category.info.discussion %>
<% category.gem_specs.each do |spec| -%>
* [<%= spec.name %>](<%= spec.name %>/README.md): <%= spec.summary %>
<% end -%>

#### Dependency Diagram

<%= category.mermaid_definition %>
<% end -%>

## Versioning Policy

ElasticGraph does _not_ strictly follow the [SemVer](https://semver.org/) spec. We followed that early in the project's life
cycle and realized that it obscures some important compatibility information.

ElasticGraph's versioning policy is designed to communicate compatibility information related to the following stakeholders:

* **Application maintainers**: engineers that define an ElasticGraph schema, maintain project configuration, and perform upgrades.
* **Data publishers**: systems that publish data into an ElasticGraph application for ingestion by an ElasticGraph indexer.
* **GraphQL clients**: clients of the GraphQL API of an ElasticGraph application.

We use the following versioning scheme:

* Version numbers are in a `0.MAJOR.MINOR.PATCH` format. (The `0.` prefix is there in order to reserve `1.0.0` and all later versions
  for after ElasticGraph has been open-sourced).
* Increments to the PATCH version indicate that the new release contains no backwards incompatibilities for any stakeholders.
  It may contain bug fixes, new features, internal refactorings, and dependency upgrades, among other things. You can expect that
  PATCH level upgrades are always safe--just update the version in your bundle, generate new schema artifacts, and you should be done.
* Increments to the MINOR version indicate that the new release contains some backwards incompatibilities that may impact the
  **application maintainers** of some ElasticGraph applications. MINOR releases may include renames to configuration settings,
  changes to the schema definition API, and new schema definition requirements, among other things. You can expect that MINOR
  level upgrades can usually be done in 30 minutes or less (usually in a single commit!), with release notes and clear errors
  from ElasticGraph command line tasks providing guidance on how to upgrade.
* Increments to the MAJOR version indicate that the new release contains some backwards incompatibilities that may impact the
  **data publishers** or **GraphQL clients** of some ElasticGraph applications. MAJOR releases may include changes to the GraphQL
  schema that require careful migration of **GraphQL clients** or changes to how indexing is done that require a dataset to be
  re-indexed from scratch (e.g. by having **data publishers** republish their data into an ElasticGraph indexer running the new
  version). You can expect that the release notes will include detailed instructions on how to perform a MAJOR version upgrade.

Deprecation warnings may be included at any of these levels--for example, a PATCH release may contain a deprecation warning
for a breaking change that may impact **application maintainers** in an upcoming MINOR release, and a MINOR release may
contain deprecation warnings for breaking changes that may impact **data publishers** or **GraphQL clients** in an upcoming
MAJOR release.

Each version level is cumulative over the prior levels. That is, a MINOR release may include PATCH-level changes in addition
to backwards incompatibilities that may impact **application maintainers**. A MAJOR release may include PATCH-level or
MINOR-level changes in addition to backwards incompatibilities that may impact **data publishers** or **GraphQL clients**.

Note that this policy was first adopted in the `v0.15.1.0` release.  All prior releases aimed (with some occasional mistakes!)
to follow SemVer with a `0.MAJOR.MINOR.PATCH` versioning scheme.

Note that _all_ gems in this repository share the same version number. Every time we cut a release, we increment the version
for _all_ gems and release _all_ gems, even if a gem has had no changes since the last release. This is simpler to work with
than the alternatives.

## License

ElasticGraph is released under the [MIT License](https://opensource.org/licenses/MIT).

[Part of the distributed code](elasticgraph-rack/lib/elastic_graph/rack/graphiql/index.html)
comes from the [GraphiQL project](https://github.com/graphql/graphiql), also licensed under the
MIT License, Copyright (c) GraphQL Contributors.
