module ElasticGraph
  module SchemaDefinition
    module Indexing
      module EventEnvelope
        def self.json_schema: (::Array[::String], ::Integer) -> ::Hash[::String, untyped]
      end
    end
  end
end
