module ElasticGraph
  module SchemaDefinition
    module Indexing
      class JSONSchemaFieldMetadata
        attr_reader type: ::String
        attr_reader name_in_index: ::String

        def initialize: (
          type: ::String,
          name_in_index: ::String
        ) -> void

        def to_dumpable_hash: () -> {"type" => ::String, "nameInIndex" => ::String}
      end
    end
  end
end
