module ElasticGraph
  module QueryRegistry
    module GraphQLExtension: GraphQL
      def graphql_query_executor: () -> RegistryAwareQueryExecutor
    end

    class RegistryAwareQueryExecutor < GraphQL::QueryExecutor
      def initialize: (
        registry_directory: ::String,
        allow_unregistered_clients: bool,
        allow_any_query_for_clients: ::Array[::String],
        schema: GraphQL::Schema,
        monotonic_clock: Support::MonotonicClock,
        logger: ::Logger,
        slow_query_threshold_ms: ::Integer,
        datastore_search_router: GraphQL::DatastoreSearchRouter
      ) -> void

      private

      @registry: Registry
    end

    class ConfigSupertype
      attr_reader path_to_registry: ::String
      attr_reader allow_unregistered_clients: bool
      attr_reader allow_any_query_for_clients: ::Array[::String]

      def self.new: (
        path_to_registry: ::String,
        allow_unregistered_clients: bool,
        allow_any_query_for_clients: ::Array[::String]
      ) -> Config

      def with: (
        ?path_to_registry: ::String,
        ?allow_unregistered_clients: bool,
        ?allow_any_query_for_clients: ::Array[::String]
      ) -> Config
    end

    class Config < ConfigSupertype
      extend _BuildableFromParsedYaml[Config]
      DEFAULT: Config
    end
  end

  class Config
    attr_reader query_registry: QueryRegistry::Config
  end
end
