module ElasticGraph
  class IndexerAutoscalerLambda
    class ConcurrencyScaler
      def initialize: (
        datastore_core: DatastoreCore,
        sqs_client: Aws::SQS::Client,
        lambda_client: Aws::Lambda::Client
      ) -> void

      MINIMUM_CONCURRENCY: ::Integer

      def tune_indexer_concurrency: (
        queue_urls: ::Array[::String],
        min_cpu_target: ::Integer,
        max_cpu_target: ::Integer,
        maximum_concurrency: ::Integer,
        indexer_function_name: ::String
      ) -> void

      private

      @logger: ::Logger
      @datastore_core: DatastoreCore
      @sqs_client: Aws::SQS::Client
      @lambda_client: Aws::Lambda::Client

      def get_max_cpu_utilization: () -> ::Float
      def get_queue_attributes: (::Array[::String]) -> { total_messages: ::Integer, queue_arns: ::Array[::String] }
      def get_concurrency: (::String) -> ::Integer?

      def update_concurrency: (
        indexer_function_name: ::String,
        concurrency: ::Integer,
        maximum_concurrency: ::Integer
      ) -> void
    end
  end
end
