module ElasticGraph
  class Admin
    class ClusterConfigurator
      class ClusterSettingsManager
        type clusterSpec = ::String | :all_clusters

        def initialize: (
          datastore_clients_by_name: ::Hash[::String, DatastoreCore::_Client],
          datastore_config: DatastoreCore::Config,
          logger: ::Logger) -> void

        def start_index_maintenance_mode!: (clusterSpec) -> void
        def end_index_maintenance_mode!: (clusterSpec) -> void
        def in_index_maintenance_mode: (clusterSpec) { () -> void } -> void

        private

        @datastore_clients_by_name: ::Hash[::String, DatastoreCore::_Client]
        @datastore_config: DatastoreCore::Config
        @logger: ::Logger

        def desired_cluster_settings: (::String, ?auto_create_index_patterns: ::Array[::String]) -> ::Hash[::String, untyped]
        def datastore_client_named: (::String) -> DatastoreCore::_Client
        def cluster_names_for: (clusterSpec) -> ::Array[::String]
      end
    end
  end
end
