module ElasticGraph
  class GraphQL
    module Resolvers
      class GetRecordFieldValue
        include _Resolver

        def initialize: (
          schema_element_names: SchemaArtifacts::RuntimeMetadata::SchemaElementNames
        ) -> void
      end
    end
  end
end
