module ElasticGraph
  class GraphQL
    module Resolvers
      class GraphQLAdapter
        def initialize: (
          schema: Schema,
          datastore_query_builder: DatastoreQuery::Builder,
          datastore_query_adapters: ::Array[_QueryAdapter],
          runtime_metadata: SchemaArtifacts::RuntimeMetadata::Schema,
          resolvers: ::Array[Resolvers::_Resolver]
        ) -> void
      end
    end
  end
end
