module ElasticGraph
  module SchemaDefinition
    class RakeTasks < ::Rake::TaskLib
      def initialize: (
        index_document_sizes: bool,
        path_to_schema: ::String | ::Pathname,
        schema_artifacts_directory: ::String | ::Pathname,
        schema_element_name_form: :camelCase | :snake_case,
        ?schema_element_name_overrides: ::Hash[::Symbol, ::String],
        ?derived_type_name_formats: ::Hash[::Symbol, ::String],
        ?type_name_overrides: ::Hash[::Symbol, ::String],
        ?enum_value_overrides_by_type: ::Hash[::Symbol, ::Hash[::Symbol, ::String]],
        ?extension_modules: ::Array[::Module],
        ?enforce_json_schema_version: bool,
        ?output: io
      ) -> void

      private

      @derived_type_name_formats: ::Hash[::Symbol, ::String]
      @type_name_overrides: ::Hash[::Symbol, ::String]
      @enum_value_overrides_by_type: ::Hash[::Symbol, ::Hash[::Symbol, ::String]]
      @schema_element_names: SchemaArtifacts::RuntimeMetadata::SchemaElementNames
      @index_document_sizes: bool
      @path_to_schema: ::String | ::Pathname
      @schema_artifacts_directory: ::String | ::Pathname
      @enforce_json_schema_version: bool
      @extension_modules: ::Array[::Module]
      @output: io

      def define_tasks: () -> void
      def schema_artifact_manager: () -> SchemaArtifactManager
      def schema_definition_results: () -> Results
    end
  end
end
